# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
---
include:
  - board: seeeduino_xiao_ble
    shield: totem_left rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: totem_right rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: totem_dongle rgbled_adapter
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: settings_reset
